import * as Yup from "yup";
export const addproductSchema = Yup.object().shape({
    name: Yup.string().required("Product name is required"),
    category: Yup.string().required("Category is required"),
    brand: Yup.string().required("Brand is required"),
    color: Yup.string().required("Color is required"),
    material: Yup.string().required("Material is required"),
    size: Yup.string().required("size is required"),
    description: Yup.string().required("description is required"),
    featured: Yup.boolean(),
    price: Yup.number().required("Price is required"),
    discount: Yup.number(),
    discountPrice: Yup.number(),
    discountStartDate: Yup.date(),
    discountEndDate: Yup.date(),
    tax: Yup.number(),
    totalStockQuantity: Yup.number().required("Total stock quantity is required"),
    availableStock: Yup.number().required("Available stock is required"),
    stockStatus: Yup.string().required("Stock status is required"),
  });